replicaCount: 1

port: 4000

canary:
  enabled: false

normal_deploy:
  enabled: true

version: api-v1

istio_url: api.anderondelima.com

image:
  repository: anderondev/sample
  pullPolicy: Always
  tag: latest
  containerPort: 4000
  livenessProbe:
    path: /
    port: 4000
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /
    port: 4000
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: api

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000


resources:
  requests:
    cpu: 10m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
nodeSelector: {}

tolerations: []

affinity: {}
